import assert from 'assert';
import type { CodegenConfig } from '@graphql-codegen/cli';

const { CONTELLO_URL, CONTELLO_STORE_PROJECT, CONTELLO_TOKEN } = process.env;

assert(CONTELLO_URL, 'CONTELLO_URL is required');
assert(CONTELLO_STORE_PROJECT, 'CONTELLO_STORE_PROJECT is required');
assert(CONTELLO_TOKEN, 'CONTELLO_TOKEN is required');

const generatedNote = `/* eslint-disable */
/* @ts-ignore */
/*

  This file is generated by graphql-codegen. Do not edit it manually.

*/`;

const config: CodegenConfig = {
  schema: {
    [`${CONTELLO_URL}/graphql/projects/${CONTELLO_STORE_PROJECT}`]: {
      headers: {
        authorization: `Bearer ${CONTELLO_TOKEN}`,
      },
    },
  },
  generates: {
    'src/generated/graphql.ts': {
      documents: ['fragments/**/*.gql', 'graphql/**/*.gql'],
      plugins: [{ add: { content: generatedNote } }, 'typescript', 'typescript-operations'],
      config: {
        enumsAsTypes: true,
        useTypeImports: true,
        dedupeFragments: true,
        skipTypename: false,
        avoidOptionals: {
          field: true,
          inputValue: false,
          object: true,
          defaultValue: false,
        },
      },
    },
  },
};

export default config;
