/* eslint-disable */
// @ts-nocheck
/* this file is generated by contello-client — do not edit */

import type { LocalDate, LocalDateTime, SourceDef } from '@contello/client';

export type ContelloAssetKind = 'AUDIO' | 'DOCUMENT' | 'IMAGE' | 'OTHER' | 'VIDEO';
export type ContelloAssetRetentionPolicy = 'deleteIfNotUsed' | 'retain';
export type ContelloBatchOperationStatus = 'error' | 'success';
export type ContelloContentDispositionEnum = 'ATTACHMENT' | 'AUTOMATIC' | 'INLINE';
export type ContelloDictionaryType = 'ENTITY' | 'STATIC';
export type ContelloMutationType = 'CREATE' | 'DELETE' | 'UPDATE';
export type ContelloRouteTargetTypeEnum = 'ENTITY' | 'FILE' | 'REDIRECT' | 'TEXT_RESPONSE';
export type SectionAppearanceStaticDictionary = 'dark' | 'light';
export type ShippingOptionsStaticDictionary = 'delivery' | 'selfPickup';

export type CategoriesFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type CategoriesRequestInput = {
  filter?: CategoriesFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type CategoryAttributesInput = {
  name?: string | undefined;
};

export type ConfigAttributesInput = {
  brandName?: string | undefined;
};

export type ContelloAnnotationFilterInput = {
  key?: string | undefined;
  value?: string | undefined;
};

export type ContelloAssetAnnotationInput = {
  key: string;
  value: string;
};

export type ContelloAssetInput = {
  assetId: string;
};

export type ContelloAssetRequestInput = {
  id?: string | undefined;
};

export type ContelloAssetsFilterInput = {
  annotations?: (ContelloAnnotationFilterInput | undefined)[] | undefined;
  collectionReferences?: (string | undefined)[] | undefined;
  ids?: (string | undefined)[] | undefined;
  kinds?: (ContelloAssetKind | undefined)[] | undefined;
};

export type ContelloAssetsPaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ContelloAssetUpdateInput = {
  annotations?: ContelloAssetAnnotationInput[] | undefined;
  collectionIds?: string[] | undefined;
  collectionReferenceNames?: string[] | undefined;
  id: string;
  name?: string | undefined;
  retentionPolicy?: ContelloAssetRetentionPolicy | undefined;
  tags?: string[] | undefined;
};

export type ContelloEntityRouteInput = {
  path: string;
};

export type ContelloI18nMessageInput = {
  description?: string | undefined;
  example?: string | undefined;
  initialTranslations?: ContelloI18nMessageTranslationValueInput[] | undefined;
  token: string;
  translations?: ContelloI18nMessageTranslationValueInput[] | undefined;
  variables?: ContelloI18nMessageVariableInput[] | undefined;
};

export type ContelloI18nMessagePaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ContelloI18nMessageTranslationValueInput = {
  language: string;
  message: string;
};

export type ContelloI18nMessageVariableInput = {
  description?: string | undefined;
  example?: string | undefined;
  name: string;
};

export type ContelloRichTextInput = {
  _markdownData?: string | undefined;
  _serializedData?: string | undefined;
  serializedData?: string | undefined;
};

export type ContelloRouteHeaderInput = {
  name: string;
  value: string;
};

export type ContelloRouteInput = {
  customHeaders?: (ContelloRouteHeaderInput | undefined)[] | undefined;
  path: string;
  targetEntityConfig?: TargetEntityConfigInput | undefined;
  targetFileConfig?: TargetFileConfig | undefined;
  targetRedirectConfig?: TargetRedirectConfig | undefined;
  targetTextResponseConfig?: TargetTextResponseConfig | undefined;
  targetType: ContelloRouteTargetTypeEnum;
};

export type ContelloRouteRequestInput = {
  id?: string | undefined;
  path?: string | undefined;
};

export type ContelloRoutesRequestInput = {
  ids?: (string | undefined)[] | undefined;
  paths?: (string | undefined)[] | undefined;
  targetType?: ContelloRouteTargetTypeEnum | undefined;
};

export type CreateCategoryEntityInput = {
  attributes: CategoryAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateCategoryRequestInput = {
  entity: CreateCategoryEntityInput;
};

export type CreateProductEntityInput = {
  attributes: ProductAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateProductRequestInput = {
  entity: CreateProductEntityInput;
};

export type CreateStaticPageEntityInput = {
  attributes: StaticPageAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateStaticPageRequestInput = {
  entity: CreateStaticPageEntityInput;
};

export type DateTimeFilterInput = {
  between?: DateTimeRangeInput | undefined;
  equal?: string | undefined;
  exists?: boolean | undefined;
  greaterThan?: string | undefined;
  greaterThanEqual?: string | undefined;
  lessThan?: string | undefined;
  lessThanEqual?: string | undefined;
  notEqual?: string | undefined;
};

export type DateTimeRangeInput = {
  from: string;
  to: string;
};

export type DeleteEntityByIdInput = {
  force?: boolean | undefined;
  id: string;
};

export type DeleteEntityByIdsInput = {
  ids: string[];
};

export type GetEntityByIdInput = {
  id: string;
};

export type PaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ProductAttributesInput = {
  activeSince?: LocalDateTime | undefined;
  bestBefore?: LocalDate | undefined;
  category?: string | undefined;
  description?: ContelloRichTextInput | undefined;
  image?: ContelloAssetInput | undefined;
  name?: string | undefined;
  shipping?: (ShippingOptionsStaticDictionary | undefined)[] | undefined;
};

export type ProductListComponentInput = {
  headline?: string | undefined;
  products?: (string | undefined)[] | undefined;
};

export type ProductsFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type ProductsRequestInput = {
  filter?: ProductsFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type SectionComponentInput = {
  appearance?: SectionAppearanceStaticDictionary | undefined;
  content?: (SectionContentMixedComponentArrayItemInput | undefined)[] | undefined;
  headline?: string | undefined;
};

export type SectionContentMixedComponentArrayItemInput = {
  textComponent?: TextComponentInput | undefined;
};

export type StaticPageAttributesInput = {
  content?: (StaticPageContentMixedComponentArrayItemInput | undefined)[] | undefined;
  name?: string | undefined;
};

export type StaticPageContentMixedComponentArrayItemInput = {
  productListComponent?: ProductListComponentInput | undefined;
  sectionComponent?: SectionComponentInput | undefined;
  textComponent?: TextComponentInput | undefined;
};

export type StaticPagesFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type StaticPagesRequestInput = {
  filter?: StaticPagesFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type StringFilterInput = {
  contains?: string | undefined;
  endsWith?: string | undefined;
  equal?: string | undefined;
  exists?: boolean | undefined;
  in?: string[] | undefined;
  notEqual?: string | undefined;
  notIn?: string[] | undefined;
  startsWith?: string | undefined;
};

export type TargetEntityConfigInput = {
  entityId: string;
  entityModelId: string;
};

export type TargetFileConfig = {
  assetId: string;
  contentDisposition: ContelloContentDispositionEnum;
};

export type TargetRedirectConfig = {
  location: string;
  responseCode: number;
};

export type TargetTextResponseConfig = {
  content: string;
  mimeType: string;
};

export type TextComponentInput = {
  text?: ContelloRichTextInput | undefined;
};

export type UpdateCategoryEntityInput = {
  attributes: CategoryAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateCategoryRequestInput = {
  entity: UpdateCategoryEntityInput;
};

export type UpdateConfigEntityInput = {
  attributes: ConfigAttributesInput;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export type UpdateConfigRequestInput = {
  entity: UpdateConfigEntityInput;
};

export type UpdateProductEntityInput = {
  attributes: ProductAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateProductRequestInput = {
  entity: UpdateProductEntityInput;
};

export type UpdateStaticPageEntityInput = {
  attributes: StaticPageAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateStaticPageRequestInput = {
  entity: UpdateStaticPageEntityInput;
};

export type CategoriesResponseCollection = {
  __typename?: 'CategoriesResponseCollection' | undefined;
  entities: CategoryEntity[];
  pagination: Pagination;
};

export type CategoryAttributes = {
  __typename?: 'CategoryAttributes' | undefined;
  name?: string | undefined;
};

export type CategoryEntity = {
  __typename?: 'CategoryEntity' | undefined;
  __model?: 'category' | undefined;
  attributes: CategoryAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type CategoryEntityUpdate = {
  __typename?: 'CategoryEntityUpdate' | undefined;
  entity: CategoryEntity;
  mutation: ContelloMutation;
};

export type ConfigAttributes = {
  __typename?: 'ConfigAttributes' | undefined;
  brandName?: string | undefined;
};

export type ConfigEntity = {
  __typename?: 'ConfigEntity' | undefined;
  __model?: 'config' | undefined;
  attributes: ConfigAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  updatedAt: string;
};

export type ConfigEntityUpdate = {
  __typename?: 'ConfigEntityUpdate' | undefined;
  entity: ConfigEntity;
  mutation: ContelloMutation;
};

export type ContelloAsset = {
  __typename?: 'ContelloAsset' | undefined;
  annotations: ContelloAssetAnnotation[];
  createdAt: string;
  id: string;
  optimized: ContelloOptimizedFile[];
  original: ContelloFile;
  preview?: ContelloFile | undefined;
  updatedAt: string;
};

export type ContelloAssetAnnotation = {
  __typename?: 'ContelloAssetAnnotation' | undefined;
  key: string;
  value: string;
};

export type ContelloAssetDeleteResponse = {
  __typename?: 'ContelloAssetDeleteResponse' | undefined;
  id: string;
  status: ContelloBatchOperationStatus;
};

export type ContelloBatchOperationResponse = {
  __typename?: 'ContelloBatchOperationResponse' | undefined;
  status: ContelloBatchOperationStatus;
};

export type ContelloDictionary = {
  __typename?: 'ContelloDictionary' | undefined;
  createdAt: string;
  description?: string | undefined;
  id: string;
  items?: (string | undefined)[] | undefined;
  name: string;
  referenceName: string;
  type: ContelloDictionaryType;
  updatedAt: string;
};

export type ContelloEntityDeleteResponse = {
  __typename?: 'ContelloEntityDeleteResponse' | undefined;
  id: string;
  status: ContelloBatchOperationStatus;
};

export type ContelloEntityModel = {
  __typename?: 'ContelloEntityModel' | undefined;
  description: string;
  id: string;
  isRoutable: boolean;
  name: string;
  referenceName: string;
};

export type ContelloI18nMessage = {
  __typename?: 'ContelloI18nMessage' | undefined;
  collectionId: string;
  createdAt: string;
  deprecated: boolean;
  description?: string | undefined;
  example?: string | undefined;
  id: string;
  token: string;
  translations: ContelloI18nMessageTranslation[];
  updatedAt: string;
  variables?: ContelloI18nMessageVariable[] | undefined;
};

export type ContelloI18nMessagePagination = {
  __typename?: 'ContelloI18nMessagePagination' | undefined;
  limit: number;
  offset: number;
  total: number;
};

export type ContelloI18nMessageRegisterResponse = {
  __typename?: 'ContelloI18nMessageRegisterResponse' | undefined;
  ids: string[];
};

export type ContelloI18nMessagesResponse = {
  __typename?: 'ContelloI18nMessagesResponse' | undefined;
  items: ContelloI18nMessage[];
  pagination: ContelloI18nMessagePagination;
};

export type ContelloI18nMessageTranslation = {
  __typename?: 'ContelloI18nMessageTranslation' | undefined;
  language: string;
  value: string;
};

export type ContelloI18nMessageUpdate = {
  __typename?: 'ContelloI18nMessageUpdate' | undefined;
  message: ContelloI18nMessage;
  mutation: ContelloMutation;
};

export type ContelloI18nMessageVariable = {
  __typename?: 'ContelloI18nMessageVariable' | undefined;
  description?: string | undefined;
  example?: string | undefined;
  name: string;
};

export type ContelloImageMetadata = {
  __typename?: 'ContelloImageMetadata' | undefined;
  height: number;
  width: number;
};

export type ContelloImageOptimizationConfig = {
  __typename?: 'ContelloImageOptimizationConfig' | undefined;
  name: string;
};

export type ContelloMutation = {
  __typename?: 'ContelloMutation' | undefined;
  type: ContelloMutationType;
};

export type ContelloOptimizedFile = {
  __typename?: 'ContelloOptimizedFile' | undefined;
  fileName: string;
  metadata?: ContelloFileMetadata | undefined;
  mimeType: string;
  optimizationConfig?: ContelloOptimizationConfig | undefined;
  uid: string;
};

export type ContelloProject = {
  __typename?: 'ContelloProject' | undefined;
  description: string;
  id: string;
  name: string;
  referenceName: string;
};

export type ContelloRichText = {
  __typename?: 'ContelloRichText' | undefined;
  markdownData?: string | undefined;
  serializedData?: string | undefined;
};

export type ContelloRoute = {
  __typename?: 'ContelloRoute' | undefined;
  createdAt: string;
  customHeaders: ContelloRouteHeader[];
  id: string;
  path: string;
  target: ContelloRouteTarget;
  updatedAt: string;
};

export type ContelloRouteHeader = {
  __typename?: 'ContelloRouteHeader' | undefined;
  name: string;
  value: string;
};

export type ContelloRouteTargetAsset = {
  __typename?: 'ContelloRouteTargetAsset' | undefined;
  asset: ContelloAsset;
  contentDisposition: ContelloContentDispositionEnum;
};

export type ContelloRouteTargetEntity = {
  __typename?: 'ContelloRouteTargetEntity' | undefined;
  entity?: ContelloEntityBase | undefined;
};

export type ContelloRouteTargetRedirect = {
  __typename?: 'ContelloRouteTargetRedirect' | undefined;
  location: string;
  responseCode: number;
};

export type ContelloRouteTargetText = {
  __typename?: 'ContelloRouteTargetText' | undefined;
  content: string;
  mimeType: string;
};

export type ContelloRouteUpdate = {
  __typename?: 'ContelloRouteUpdate' | undefined;
  mutation: ContelloMutation;
  route: ContelloRoute;
};

export type ContelloUpdateBatch = {
  __typename?: 'ContelloUpdateBatch' | undefined;
  events: ContelloUpdateEvent[];
};

export type ContelloUpdateEvent = {
  __typename?: 'ContelloUpdateEvent' | undefined;
  mutation: ContelloMutation;
  prev?: ContelloUpdatePrev | undefined;
  target: ContelloUpdateTarget;
};

export type ContelloVideoMetadata = {
  __typename?: 'ContelloVideoMetadata' | undefined;
  height: number;
  width: number;
};

export type ContelloVideoOptimizationConfig = {
  __typename?: 'ContelloVideoOptimizationConfig' | undefined;
  name: string;
};

export type Pagination = {
  __typename?: 'Pagination' | undefined;
  limit: number;
  offset: number;
  total: number;
};

export type PingResult = {
  __typename?: 'PingResult' | undefined;
  response: string;
};

export type ProductAttributes = {
  __typename?: 'ProductAttributes' | undefined;
  activeSince?: LocalDateTime | undefined;
  bestBefore?: LocalDate | undefined;
  category?: CategoryEntity | undefined;
  description?: ContelloRichText | undefined;
  image?: ContelloAsset | undefined;
  name?: string | undefined;
  shipping?: ShippingOptionsStaticDictionary[] | undefined;
};

export type ProductEntity = {
  __typename?: 'ProductEntity' | undefined;
  __model?: 'product' | undefined;
  attributes: ProductAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type ProductEntityUpdate = {
  __typename?: 'ProductEntityUpdate' | undefined;
  entity: ProductEntity;
  mutation: ContelloMutation;
};

export type ProductListComponent = {
  __typename?: 'ProductListComponent' | undefined;
  __model?: 'productList' | undefined;
  _flatId?: string | undefined;
  headline?: string | undefined;
  products?: ProductEntity[] | undefined;
};

export type ProductsResponseCollection = {
  __typename?: 'ProductsResponseCollection' | undefined;
  entities: ProductEntity[];
  pagination: Pagination;
};

export type RootMutation = {
  __typename?: 'RootMutation' | undefined;
  createCategories?: CategoryEntity[] | undefined;
  createCategory?: CategoryEntity | undefined;
  createContelloRoute?: ContelloRoute | undefined;
  createContelloRoutes?: ContelloRoute[] | undefined;
  createProduct?: ProductEntity | undefined;
  createProducts?: ProductEntity[] | undefined;
  createStaticPage?: StaticPageEntity | undefined;
  createStaticPages?: StaticPageEntity[] | undefined;
  deleteCategories?: ContelloEntityDeleteResponse[] | undefined;
  deleteCategory: ContelloEntityDeleteResponse;
  deleteConfig: ContelloEntityDeleteResponse;
  deleteContelloAsset: ContelloAssetDeleteResponse;
  deleteContelloRoute: string;
  deleteProduct: ContelloEntityDeleteResponse;
  deleteProducts?: ContelloEntityDeleteResponse[] | undefined;
  deleteStaticPage: ContelloEntityDeleteResponse;
  deleteStaticPages?: ContelloEntityDeleteResponse[] | undefined;
  registerContelloI18nMessages?: ContelloI18nMessageRegisterResponse | undefined;
  truncateCategories?: ContelloBatchOperationResponse | undefined;
  truncateContelloRoutes?: ContelloBatchOperationResponse | undefined;
  truncateProducts?: ContelloBatchOperationResponse | undefined;
  truncateStaticPages?: ContelloBatchOperationResponse | undefined;
  updateCategories?: CategoryEntity[] | undefined;
  updateCategory?: CategoryEntity | undefined;
  updateConfig?: ConfigEntity | undefined;
  updateContelloAsset?: ContelloAsset | undefined;
  updateContelloRoute?: ContelloRoute | undefined;
  updateProduct?: ProductEntity | undefined;
  updateProducts?: ProductEntity[] | undefined;
  updateStaticPage?: StaticPageEntity | undefined;
  updateStaticPages?: StaticPageEntity[] | undefined;
};

export type RootQuery = {
  __typename?: 'RootQuery' | undefined;
  categories: CategoriesResponseCollection;
  category?: CategoryEntity | undefined;
  config?: ConfigEntity | undefined;
  contelloAsset?: ContelloAsset | undefined;
  contelloAssets?: (ContelloAsset | undefined)[] | undefined;
  contelloDictionaries?: (ContelloDictionary | undefined)[] | undefined;
  contelloEntityModels?: (ContelloEntityModel | undefined)[] | undefined;
  contelloI18nMessages?: ContelloI18nMessagesResponse | undefined;
  contelloPing: PingResult;
  contelloProject?: ContelloProject | undefined;
  contelloRoute?: ContelloRoute | undefined;
  contelloRoutes?: (ContelloRoute | undefined)[] | undefined;
  product?: ProductEntity | undefined;
  products: ProductsResponseCollection;
  staticPage?: StaticPageEntity | undefined;
  staticPages: StaticPagesResponseCollection;
};

export type RootSubscription = {
  __typename?: 'RootSubscription' | undefined;
  categories?: CategoryEntity | undefined;
  categoriesBatch: CategoryEntity[];
  categoryUpdates?: CategoryEntityUpdate | undefined;
  config?: ConfigEntity | undefined;
  configUpdates?: ConfigEntityUpdate | undefined;
  contelloAssets?: ContelloAsset | undefined;
  contelloAssetsBatch: ContelloAsset[];
  contelloI18nMessages?: ContelloI18nMessage | undefined;
  contelloI18nMessagesBatch: ContelloI18nMessage[];
  contelloI18nMessageUpdates?: ContelloI18nMessageUpdate | undefined;
  contelloRoutes?: ContelloRoute | undefined;
  contelloRoutesBatch: ContelloRoute[];
  contelloRouteUpdates?: ContelloRouteUpdate | undefined;
  contelloUpdates?: ContelloUpdateEvent | undefined;
  contelloUpdatesBatch?: ContelloUpdateBatch | undefined;
  products?: ProductEntity | undefined;
  productsBatch: ProductEntity[];
  productUpdates?: ProductEntityUpdate | undefined;
  staticPages?: StaticPageEntity | undefined;
  staticPagesBatch: StaticPageEntity[];
  staticPageUpdates?: StaticPageEntityUpdate | undefined;
};

export type SectionComponent = {
  __typename?: 'SectionComponent' | undefined;
  __model?: 'section' | undefined;
  _flat_content?: ContelloComponent[] | undefined;
  _flatId?: string | undefined;
  appearance?: SectionAppearanceStaticDictionary | undefined;
  content?: ContelloComponent[] | undefined;
  headline?: string | undefined;
};

export type StaticPageAttributes = {
  __typename?: 'StaticPageAttributes' | undefined;
  _flat_content?: ContelloComponent[] | undefined;
  content?: ContelloComponent[] | undefined;
  name?: string | undefined;
};

export type StaticPageEntity = {
  __typename?: 'StaticPageEntity' | undefined;
  __model?: 'staticPage' | undefined;
  attributes: StaticPageAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type StaticPageEntityUpdate = {
  __typename?: 'StaticPageEntityUpdate' | undefined;
  entity: StaticPageEntity;
  mutation: ContelloMutation;
};

export type StaticPagesResponseCollection = {
  __typename?: 'StaticPagesResponseCollection' | undefined;
  entities: StaticPageEntity[];
  pagination: Pagination;
};

export type TextComponent = {
  __typename?: 'TextComponent' | undefined;
  __model?: 'text' | undefined;
  _flatId?: string | undefined;
  text?: ContelloRichText | undefined;
};

export type ContelloEntityBase = {
  __typename?: string | undefined;
  createdAt: string;
  id: string;
  updatedAt: string;
};

export type ContelloFile = {
  __typename?: string | undefined;
  fileName: string;
  metadata?: ContelloFileMetadata | undefined;
  mimeType: string;
  uid: string;
};

export type ContelloFlatComponent = {
  __typename?: string | undefined;
  _flatId?: string | undefined;
};

export type ContelloComponent = ProductListComponent | SectionComponent | TextComponent;
export type ContelloEntity = CategoryEntity | ConfigEntity | ProductEntity | StaticPageEntity;
export type ContelloFileMetadata = ContelloImageMetadata | ContelloVideoMetadata;
export type ContelloOptimizationConfig = ContelloImageOptimizationConfig | ContelloVideoOptimizationConfig;
export type ContelloRouteTarget = ContelloRouteTargetAsset | ContelloRouteTargetEntity | ContelloRouteTargetRedirect | ContelloRouteTargetText;
export type ContelloUpdatePrev = ContelloRoute;
export type ContelloUpdateTarget = CategoryEntity | ConfigEntity | ContelloAsset | ContelloI18nMessage | ContelloRoute | ProductEntity | StaticPageEntity;

export type MediaFileFragment = {
  uid: string;
  mimeType: string;
  metadata?: {
    __typename: 'ContelloImageMetadata';
    width: number;
    height: number;
  } | {
    __typename: 'ContelloVideoMetadata';
    width: number;
    height: number;
  } | undefined;
};

export type MediaAssetFragment = {
  id: string;
  original: MediaFileFragment;
  preview?: MediaFileFragment | undefined;
  optimized: (MediaFileFragment & ({
    __typename: 'ContelloOptimizedFile';
    optimizationConfig?: {
      __typename: 'ContelloImageOptimizationConfig';
      name: string;
    } | undefined;
  }))[];
};

export type StoreFileFragment = MediaFileFragment;

export type StoreAssetFragment = MediaAssetFragment;

export type StoreI18nMessageFragment = {
  id: string;
  token: string;
  description?: string | undefined;
  example?: string | undefined;
  translations: ({
    language: string;
    value: string;
  })[];
};

export type StoreRouteFragment = {
  id: string;
  path: string;
  target: {
    __typename: 'ContelloRouteTargetEntity';
    entity?: {
      __typename: string;
      id: string;
    } | undefined;
  } | {
    __typename: 'ContelloRouteTargetAsset';
    asset: {
      id: string;
      original: {
        uid: string;
        mimeType: string;
      };
    };
    contentDisposition: ContelloContentDispositionEnum;
  } | {
    __typename: 'ContelloRouteTargetRedirect';
    location: string;
    responseCode: number;
  } | {
    __typename: 'ContelloRouteTargetText';
    content: string;
    mimeType: string;
  };
  customHeaders: ({
    name: string;
    value: string;
  })[];
};

export type CategoryFragment = {
  id: string;
  attributes: {
    name?: string | undefined;
  };
};

export type ComponentFragment = {
  __typename: 'ProductListComponent';
  __model: 'productList';
  headline?: string | undefined;
  products?: ({
    id: string;
  })[] | undefined;
} | {
  __typename: 'TextComponent';
  __model: 'text';
  text?: {
    markdownData?: string | undefined;
  } | undefined;
} | {
  __typename: 'SectionComponent';
  __model: 'section';
  headline?: string | undefined;
  content?: ComponentFragment[] | undefined;
};

export type ConfigFragment = {
  attributes: {
    brandName?: string | undefined;
  };
};

export type ProductFragment = {
  id: string;
  internalName: string;
  routes: ({
    path: string;
  })[];
  attributes: {
    name?: string | undefined;
    activeSince?: LocalDateTime | undefined;
    bestBefore?: LocalDate | undefined;
    description?: {
      markdownData?: string | undefined;
    } | undefined;
    image?: StoreAssetFragment | undefined;
    category?: {
      id: string;
    } | undefined;
  };
};

export type StaticPageFragment = {
  id: string;
  internalName: string;
  routes: ({
    path: string;
  })[];
  attributes: {
    name?: string | undefined;
    content?: ComponentFragment[] | undefined;
  };
};


const CategoryFragmentSchema = `fragment Category on CategoryEntity {
  id
  attributes {
    name
  }
}`;
const ComponentFragmentSchema = `fragment Component on ContelloComponent {
  __typename
  ... on ContelloFlatComponent {
    _flatId
  }
  ... on ProductListComponent {
    headline
    products {
      id
    }
  }
  ... on TextComponent {
    text {
      markdownData
    }
  }
  ... on SectionComponent {
    headline
    content {
      ... on ContelloFlatComponent {
        _flatId
      }
    }
  }
}`;
const ConfigFragmentSchema = `fragment Config on ConfigEntity {
  attributes {
    brandName
  }
}`;
const MediaAssetFragmentSchema = `fragment MediaAsset on ContelloAsset {
  id
  original {
    ...MediaFile
  }
  preview {
    ...MediaFile
  }
  optimized {
    ...MediaFile
    ... on ContelloOptimizedFile {
      optimizationConfig {
        ... on ContelloImageOptimizationConfig {
          name
        }
      }
    }
  }
}`;
const MediaFileFragmentSchema = `fragment MediaFile on ContelloFile {
  uid
  mimeType
  metadata {
    ... on ContelloImageMetadata {
      width
      height
    }
    ... on ContelloVideoMetadata {
      width
      height
    }
  }
}`;
const ProductFragmentSchema = `fragment Product on ProductEntity {
  id
  internalName
  routes {
    path
  }
  attributes {
    name
    _ldt_activeSince: activeSince
    _ld_bestBefore: bestBefore
    description {
      markdownData
    }
    image {
      ...StoreAsset
    }
    category {
      id
    }
  }
}`;
const StaticPageFragmentSchema = `fragment StaticPage on StaticPageEntity {
  id
  internalName
  routes {
    path
  }
  attributes {
    name
    content {
      ... on ContelloFlatComponent {
        _flatId
      }
    }
    _flat_content {
      __typename
      ... on ContelloFlatComponent {
        _flatId
      }
      ...Component
    }
  }
}`;
const StoreAssetFragmentSchema = `fragment StoreAsset on ContelloAsset {
  ...MediaAsset
}`;
const StoreFileFragmentSchema = `fragment StoreFile on ContelloFile {
  ...MediaFile
}`;
const StoreI18nMessageFragmentSchema = `fragment StoreI18nMessage on ContelloI18nMessage {
  id
  token
  description
  example
  translations {
    language
    value
  }
}`;
const StoreRouteFragmentSchema = `fragment StoreRoute on ContelloRoute {
  id
  path
  target {
    __typename
    ... on ContelloRouteTargetEntity {
      entity {
        __typename
        ... on ContelloEntityBase {
          id
        }
      }
    }
    ... on ContelloRouteTargetAsset {
      asset {
        id
        original {
          uid
          mimeType
        }
      }
      contentDisposition
    }
    ... on ContelloRouteTargetRedirect {
      location
      responseCode
    }
    ... on ContelloRouteTargetText {
      content
      mimeType
    }
  }
  customHeaders {
    name
    value
  }
}`;

export type Operations = {
};

export type Sources = {
  category: SourceDef<'category', 'entity', CategoryFragment>;
  config: SourceDef<'config', 'singleton', ConfigFragment>;
  product: SourceDef<'product', 'entity', ProductFragment>;
  staticPage: SourceDef<'staticPage', 'entity', StaticPageFragment>;
  storeAsset: SourceDef<'storeAsset', 'asset', StoreAssetFragment>;
  storeI18nMessage: SourceDef<'storeI18nMessage', 'i18nMessage', StoreI18nMessageFragment>;
  storeRoute: SourceDef<'storeRoute', 'route', StoreRouteFragment>;
};

const operations: Operations = {
};

const sources: Sources = {
  category: {
    document: CategoryFragmentSchema,
    fragment: 'Category',
    subscription: 'categoriesBatch',
    __model: 'category',
    __cardinality: 'entity',
  },
  config: {
    document: ConfigFragmentSchema,
    fragment: 'Config',
    subscription: 'config',
    __model: 'config',
    __cardinality: 'singleton',
  },
  product: {
    document: `${MediaFileFragmentSchema}\n${MediaAssetFragmentSchema}\n${StoreAssetFragmentSchema}\n${ProductFragmentSchema}`,
    fragment: 'Product',
    subscription: 'productsBatch',
    __model: 'product',
    __cardinality: 'entity',
  },
  staticPage: {
    document: `${ComponentFragmentSchema}\n${StaticPageFragmentSchema}`,
    fragment: 'StaticPage',
    subscription: 'staticPagesBatch',
    __model: 'staticPage',
    __cardinality: 'entity',
  },
  storeAsset: {
    document: `${MediaFileFragmentSchema}\n${MediaAssetFragmentSchema}\n${StoreAssetFragmentSchema}`,
    fragment: 'StoreAsset',
    subscription: 'contelloAssetsBatch',
    __model: 'storeAsset',
    __cardinality: 'asset',
  },
  storeI18nMessage: {
    document: StoreI18nMessageFragmentSchema,
    fragment: 'StoreI18nMessage',
    subscription: 'contelloI18nMessagesBatch',
    __model: 'storeI18nMessage',
    __cardinality: 'i18nMessage',
  },
  storeRoute: {
    document: StoreRouteFragmentSchema,
    fragment: 'StoreRoute',
    subscription: 'contelloRoutesBatch',
    __model: 'storeRoute',
    __cardinality: 'route',
  },
};

const models = {
  category: 'CategoryEntity',
  config: 'ConfigEntity',
  product: 'ProductEntity',
  staticPage: 'StaticPageEntity',
} as const;

export const schema = { operations, sources, models };
export type Schema = typeof schema;