/* eslint-disable */
/* @ts-ignore */
/*

  This file is generated by graphql-codegen. Do not edit it manually.

*/
import { Observable } from "rxjs";
import type { DocumentNode, ExecutionResult } from 'graphql';
import gql from 'graphql-tag';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  DateTime: { input: any; output: any; }
};

/** Filter for searching by annotations. At least one of key or value must be provided. */
export type ContelloAnnotationFilterInput = {
  /** Annotation key (optional for value-only search). */
  key?: InputMaybe<Scalars['String']['input']>;
  /** Annotation value (optional for key-only search). */
  value?: InputMaybe<Scalars['String']['input']>;
};

/** Contello asset */
export type ContelloAsset = {
  __typename?: 'ContelloAsset';
  annotations: Array<ContelloAssetAnnotation>;
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  optimized: Array<ContelloOptimizedFile>;
  original: ContelloFile;
  preview?: Maybe<ContelloFile>;
  updatedAt: Scalars['DateTime']['output'];
};

/** Asset annotation */
export type ContelloAssetAnnotation = {
  __typename?: 'ContelloAssetAnnotation';
  key: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type ContelloAssetDeleteResponse = {
  __typename?: 'ContelloAssetDeleteResponse';
  id: Scalars['String']['output'];
  status: ContelloBatchOperationStatus;
};

export type ContelloAssetKind =
  | 'AUDIO'
  | 'DOCUMENT'
  | 'IMAGE'
  | 'OTHER'
  | 'VIDEO';

export type ContelloAssetRequestInput = {
  /** The ID of the asset. */
  id?: InputMaybe<Scalars['ID']['input']>;
};

export type ContelloAssetsFilterInput = {
  /** Filter assets by annotations (AND logic for multiple filters). */
  annotations?: InputMaybe<Array<InputMaybe<ContelloAnnotationFilterInput>>>;
  /** Filter assets by collection reference names. */
  collectionReferences?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  /** Filter assets by IDs. */
  ids?: InputMaybe<Array<InputMaybe<Scalars['ID']['input']>>>;
  /** Filter assets by kind. */
  kinds?: InputMaybe<Array<InputMaybe<ContelloAssetKind>>>;
};

export type ContelloAssetsPaginationInput = {
  /** Maximum number of assets to return. */
  limit?: InputMaybe<Scalars['Int']['input']>;
  /** Number of assets to skip. */
  offset?: InputMaybe<Scalars['Int']['input']>;
};

/** Result of the batch operation */
export type ContelloBatchOperationResponse = {
  __typename?: 'ContelloBatchOperationResponse';
  status: ContelloBatchOperationStatus;
};

export type ContelloBatchOperationStatus =
  | 'error'
  | 'success';

export type ContelloComponent = SectionComponent | TextComponent;

/** Content disposition of a file. */
export type ContelloContentDispositionEnum =
  /** The file should be downloaded. */
  | 'ATTACHMENT'
  /** Content-Disposition header is absent. */
  | 'AUTOMATIC'
  /** The file can be displayed inside the Web page or Browser. */
  | 'INLINE';

/** Contello dictionary. */
export type ContelloDictionary = {
  __typename?: 'ContelloDictionary';
  /** Time of creation. */
  createdAt: Scalars['DateTime']['output'];
  /** The description of the dictionary. */
  description?: Maybe<Scalars['String']['output']>;
  /** The id of the dictionary. */
  id: Scalars['ID']['output'];
  /** Dictionary data items. */
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  /** The name of the dictionary. */
  name: Scalars['String']['output'];
  /** The referenceName of the dictionary. */
  referenceName: Scalars['String']['output'];
  /** The type of the dictionary. */
  type: ContelloDictionaryType;
  /** Time of the last update. */
  updatedAt: Scalars['DateTime']['output'];
};

/** The type of the dictionary. */
export type ContelloDictionaryType =
  /** The dictionary refers to an entity. */
  | 'ENTITY'
  /** Dictionary consists of the static list items. */
  | 'STATIC';

/** All entity types defined in the project. */
export type ContelloEntity = StaticPageEntity;

/** Fields that exist on all entities */
export type ContelloEntityBase = {
  createdAt: Scalars['DateTime']['output'];
  id: Scalars['ID']['output'];
  updatedAt: Scalars['DateTime']['output'];
};

export type ContelloEntityDeleteResponse = {
  __typename?: 'ContelloEntityDeleteResponse';
  id: Scalars['String']['output'];
  status: ContelloBatchOperationStatus;
};

/** Contello entity model. */
export type ContelloEntityModel = {
  __typename?: 'ContelloEntityModel';
  /** The description name of the entity. */
  description: Scalars['String']['output'];
  /** The id of the entity. */
  id: Scalars['ID']['output'];
  /** Indicates whether entity has a route. */
  isRoutable: Scalars['Boolean']['output'];
  /** The name of the entity. */
  name: Scalars['String']['output'];
  /** The reference name of the entity model. */
  referenceName: Scalars['String']['output'];
};

export type ContelloEntityRouteInput = {
  path: Scalars['String']['input'];
};

/** Contello file */
export type ContelloFile = {
  fileName: Scalars['String']['output'];
  metadata?: Maybe<ContelloFileMetadata>;
  mimeType: Scalars['String']['output'];
  uid: Scalars['String']['output'];
};

export type ContelloFileMetadata = ContelloImageMetadata | ContelloVideoMetadata;

export type ContelloFlatComponent = {
  _flatId?: Maybe<Scalars['String']['output']>;
};

/** An i18n message with all its data. */
export type ContelloI18nMessage = {
  __typename?: 'ContelloI18nMessage';
  /** Reference to I18nMessageCollection. */
  collectionId: Scalars['String']['output'];
  /** Creation timestamp. */
  createdAt: Scalars['DateTime']['output'];
  /** Whether message is marked as deprecated. */
  deprecated: Scalars['Boolean']['output'];
  /** Message description. */
  description?: Maybe<Scalars['String']['output']>;
  /** Example usage. */
  example?: Maybe<Scalars['String']['output']>;
  /** Message ID. */
  id: Scalars['ID']['output'];
  /** Message token key. */
  token: Scalars['String']['output'];
  /** All translations for this message. */
  translations: Array<ContelloI18nMessageTranslation>;
  /** Last update timestamp. */
  updatedAt: Scalars['DateTime']['output'];
  /** Variables used in the message. */
  variables?: Maybe<Array<ContelloI18nMessageVariable>>;
};

/** Input for creating or updating an i18n message. */
export type ContelloI18nMessageInput = {
  /** Message description. */
  description?: InputMaybe<Scalars['String']['input']>;
  /** Example usage. */
  example?: InputMaybe<Scalars['String']['input']>;
  /** Initial translation values (only used when creating new tokens). */
  initialTranslations?: InputMaybe<Array<ContelloI18nMessageTranslationValueInput>>;
  /** Message token (unique within collection). */
  token: Scalars['String']['input'];
  /** Translation values to apply (overwrites existing values for both new and existing tokens). */
  translations?: InputMaybe<Array<ContelloI18nMessageTranslationValueInput>>;
  /** Variables used in the message. */
  variables?: InputMaybe<Array<ContelloI18nMessageVariableInput>>;
};

/** Pagination info for i18n messages. */
export type ContelloI18nMessagePagination = {
  __typename?: 'ContelloI18nMessagePagination';
  /** Maximum items returned. */
  limit: Scalars['Int']['output'];
  /** Items skipped. */
  offset: Scalars['Int']['output'];
  /** Total number of messages. */
  total: Scalars['Int']['output'];
};

/** Pagination input for i18n message queries. */
export type ContelloI18nMessagePaginationInput = {
  /** Maximum number of messages to return. */
  limit?: InputMaybe<Scalars['Int']['input']>;
  /** Number of messages to skip. */
  offset?: InputMaybe<Scalars['Int']['input']>;
};

/** Response from registering i18n messages. */
export type ContelloI18nMessageRegisterResponse = {
  __typename?: 'ContelloI18nMessageRegisterResponse';
  /** IDs of created/updated messages. */
  ids: Array<Scalars['ID']['output']>;
};

/** A translation value for a specific language. */
export type ContelloI18nMessageTranslation = {
  __typename?: 'ContelloI18nMessageTranslation';
  /** Language reference name. */
  language: Scalars['String']['output'];
  /** Translation value in ICU MessageFormat. */
  value: Scalars['String']['output'];
};

/** A translation value for a specific language. */
export type ContelloI18nMessageTranslationValueInput = {
  /** Language reference name (e.g., 'en', 'de'). */
  language: Scalars['String']['input'];
  /** Translation value in ICU MessageFormat. */
  message: Scalars['String']['input'];
};

/** Real-time update for i18n messages. */
export type ContelloI18nMessageUpdate = {
  __typename?: 'ContelloI18nMessageUpdate';
  /** The updated i18n message. */
  message: ContelloI18nMessage;
  /** The type of mutation (CREATE, UPDATE, DELETE). */
  mutation: ContelloMutation;
};

/** An i18n message variable placeholder. */
export type ContelloI18nMessageVariable = {
  __typename?: 'ContelloI18nMessageVariable';
  /** Variable description. */
  description?: Maybe<Scalars['String']['output']>;
  /** Example value for the variable. */
  example?: Maybe<Scalars['String']['output']>;
  /** Variable name. */
  name: Scalars['String']['output'];
};

/** Input for an i18n message variable placeholder. */
export type ContelloI18nMessageVariableInput = {
  /** Variable description. */
  description?: InputMaybe<Scalars['String']['input']>;
  /** Example value for the variable. */
  example?: InputMaybe<Scalars['String']['input']>;
  /** Variable name. */
  name: Scalars['String']['input'];
};

/** Response containing i18n messages with pagination. */
export type ContelloI18nMessagesResponse = {
  __typename?: 'ContelloI18nMessagesResponse';
  /** List of i18n messages. */
  items: Array<ContelloI18nMessage>;
  /** Pagination information. */
  pagination: ContelloI18nMessagePagination;
};

export type ContelloImageMetadata = {
  __typename?: 'ContelloImageMetadata';
  height: Scalars['Int']['output'];
  width: Scalars['Int']['output'];
};

export type ContelloImageOptimizationConfig = {
  __typename?: 'ContelloImageOptimizationConfig';
  name: Scalars['String']['output'];
};

export type ContelloMutation = {
  __typename?: 'ContelloMutation';
  /** Kind of mutation */
  type: ContelloMutationType;
};

export type ContelloMutationType =
  | 'CREATE'
  | 'DELETE'
  | 'UPDATE';

export type ContelloOptimizationConfig = ContelloImageOptimizationConfig | ContelloVideoOptimizationConfig;

export type ContelloOptimizedFile = ContelloFile & {
  __typename?: 'ContelloOptimizedFile';
  fileName: Scalars['String']['output'];
  metadata?: Maybe<ContelloFileMetadata>;
  mimeType: Scalars['String']['output'];
  optimizationConfig?: Maybe<ContelloOptimizationConfig>;
  uid: Scalars['String']['output'];
};

/** Contello project. */
export type ContelloProject = {
  __typename?: 'ContelloProject';
  /** The description of the project. */
  description: Scalars['String']['output'];
  /** The id of the project. */
  id: Scalars['ID']['output'];
  /** The name of the project. */
  name: Scalars['String']['output'];
  /** The reference name of the project. */
  referenceName: Scalars['String']['output'];
};

/** Contello rich text */
export type ContelloRichText = {
  __typename?: 'ContelloRichText';
  /** Rich text as Markdown */
  markdownData?: Maybe<Scalars['String']['output']>;
  /** Rich text as JSON (TipTap/ProseMirror format) */
  serializedData?: Maybe<Scalars['String']['output']>;
};

export type ContelloRichTextInput = {
  _markdownData?: InputMaybe<Scalars['String']['input']>;
  _serializedData?: InputMaybe<Scalars['String']['input']>;
  serializedData?: InputMaybe<Scalars['String']['input']>;
};

/** Contello route. */
export type ContelloRoute = {
  __typename?: 'ContelloRoute';
  /** Time of creation. */
  createdAt: Scalars['DateTime']['output'];
  /** Custom headers for the route. */
  customHeaders: Array<ContelloRouteHeader>;
  /** The id of the route. */
  id: Scalars['ID']['output'];
  /** Route path. */
  path: Scalars['String']['output'];
  /** The target of the route. */
  target: ContelloRouteTarget;
  /** Time of the last update. */
  updatedAt: Scalars['DateTime']['output'];
};

/** Route header key-value pair. */
export type ContelloRouteHeader = {
  __typename?: 'ContelloRouteHeader';
  /** Header name. */
  name: Scalars['String']['output'];
  /** Header value. */
  value: Scalars['String']['output'];
};

export type ContelloRouteHeaderInput = {
  /** Header name. */
  name: Scalars['String']['input'];
  /** Header value. */
  value: Scalars['String']['input'];
};

/** Contello route object. Used for creating and updating routes. */
export type ContelloRouteInput = {
  /** Custom headers for the route. */
  customHeaders?: InputMaybe<Array<InputMaybe<ContelloRouteHeaderInput>>>;
  /** Route path. */
  path: Scalars['String']['input'];
  /** The config of the target entity. */
  targetEntityConfig?: InputMaybe<TargetEntityConfigInput>;
  /** The config of the target file. */
  targetFileConfig?: InputMaybe<TargetFileConfig>;
  /** The config of the target redirect. */
  targetRedirectConfig?: InputMaybe<TargetRedirectConfig>;
  /** The config of the target text response. */
  targetTextResponseConfig?: InputMaybe<TargetTextResponseConfig>;
  /** Route target type. */
  targetType: ContelloRouteTargetTypeEnum;
};

export type ContelloRouteRequestInput = {
  /** The ID of the route. */
  id?: InputMaybe<Scalars['ID']['input']>;
  /** The path of the route. */
  path?: InputMaybe<Scalars['String']['input']>;
};

export type ContelloRouteTarget = ContelloRouteTargetAsset | ContelloRouteTargetEntity | ContelloRouteTargetRedirect | ContelloRouteTargetText;

export type ContelloRouteTargetAsset = {
  __typename?: 'ContelloRouteTargetAsset';
  /** Attached asset. */
  asset: ContelloAsset;
  /** File content disposition. */
  contentDisposition: ContelloContentDispositionEnum;
};

export type ContelloRouteTargetEntity = {
  __typename?: 'ContelloRouteTargetEntity';
  /** Linked entity. */
  entity?: Maybe<ContelloEntityBase>;
};

export type ContelloRouteTargetRedirect = {
  __typename?: 'ContelloRouteTargetRedirect';
  /** Redirect location. */
  location: Scalars['String']['output'];
  /** Redirect response code. */
  responseCode: Scalars['Int']['output'];
};

export type ContelloRouteTargetText = {
  __typename?: 'ContelloRouteTargetText';
  /** Text response content. */
  content: Scalars['String']['output'];
  /** Text response mime type. */
  mimeType: Scalars['String']['output'];
};

/** The type of the route target. */
export type ContelloRouteTargetTypeEnum =
  /** The route target is an entity. */
  | 'ENTITY'
  /** The route target is a file. */
  | 'FILE'
  /** The route target is a redirect. */
  | 'REDIRECT'
  /** The route target is a text response. */
  | 'TEXT_RESPONSE';

/** Route update */
export type ContelloRouteUpdate = {
  __typename?: 'ContelloRouteUpdate';
  /** Route mutation */
  mutation: ContelloMutation;
  /** The updated route */
  route: ContelloRoute;
};

export type ContelloRoutesRequestInput = {
  /** Route ids to filter by. */
  ids?: InputMaybe<Array<InputMaybe<Scalars['ID']['input']>>>;
  /** Route paths to filter by. */
  paths?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  /** The route target type. */
  targetType?: InputMaybe<ContelloRouteTargetTypeEnum>;
};

export type ContelloUpdateBatch = {
  __typename?: 'ContelloUpdateBatch';
  /** Batched update events */
  events: Array<ContelloUpdateEvent>;
};

export type ContelloUpdateEvent = {
  __typename?: 'ContelloUpdateEvent';
  /** Kind of mutation */
  mutation: ContelloMutation;
  /** Previous state before the mutation, if available */
  prev?: Maybe<ContelloUpdatePrev>;
  /** The updated resource */
  target: ContelloUpdateTarget;
};

export type ContelloUpdatePrev = ContelloRoute;

export type ContelloUpdateTarget = ContelloAsset | ContelloI18nMessage | ContelloRoute | StaticPageEntity;

export type ContelloVideoMetadata = {
  __typename?: 'ContelloVideoMetadata';
  height: Scalars['Int']['output'];
  width: Scalars['Int']['output'];
};

export type ContelloVideoOptimizationConfig = {
  __typename?: 'ContelloVideoOptimizationConfig';
  name: Scalars['String']['output'];
};

export type CreateStaticPageEntityInput = {
  /** Entity attributes. */
  attributes: StaticPageAttributesInput;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
  /** Entity route. */
  route?: InputMaybe<ContelloEntityRouteInput>;
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
};

/** Entity create request. */
export type CreateStaticPageRequestInput = {
  /** Entity data input. */
  entity: CreateStaticPageEntityInput;
};

/** Filter input for datetime columns. */
export type DateTimeFilterInput = {
  between?: InputMaybe<DateTimeRangeInput>;
  equal?: InputMaybe<Scalars['DateTime']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  greaterThan?: InputMaybe<Scalars['DateTime']['input']>;
  greaterThanEqual?: InputMaybe<Scalars['DateTime']['input']>;
  lessThan?: InputMaybe<Scalars['DateTime']['input']>;
  lessThanEqual?: InputMaybe<Scalars['DateTime']['input']>;
  notEqual?: InputMaybe<Scalars['DateTime']['input']>;
};

/** Range input for datetime filters. */
export type DateTimeRangeInput = {
  from: Scalars['DateTime']['input'];
  to: Scalars['DateTime']['input'];
};

/** Delete entity by id input. */
export type DeleteEntityByIdInput = {
  /** Force delete */
  force?: InputMaybe<Scalars['Boolean']['input']>;
  /** The id of the entity. */
  id: Scalars['ID']['input'];
};

/** Delete entity by IDs input. */
export type DeleteEntityByIdsInput = {
  /** The IDs of the entities. */
  ids: Array<Scalars['ID']['input']>;
};

/** Get entity by id input. */
export type GetEntityByIdInput = {
  /** The id of the entity. */
  id: Scalars['ID']['input'];
};

export type Pagination = {
  __typename?: 'Pagination';
  limit: Scalars['Int']['output'];
  offset: Scalars['Int']['output'];
  total: Scalars['Int']['output'];
};

/** Collection pagination input. */
export type PaginationInput = {
  /** The maximum number of items to return. */
  limit?: InputMaybe<Scalars['Int']['input']>;
  /** The number of items to skip before returning the first item. */
  offset?: InputMaybe<Scalars['Int']['input']>;
};

export type PingResult = {
  __typename?: 'PingResult';
  response: Scalars['String']['output'];
};

export type RootMutation = {
  __typename?: 'RootMutation';
  createContelloRoute?: Maybe<ContelloRoute>;
  createContelloRoutes?: Maybe<Array<ContelloRoute>>;
  createStaticPage?: Maybe<StaticPageEntity>;
  createStaticPages?: Maybe<Array<StaticPageEntity>>;
  deleteContelloAsset: ContelloAssetDeleteResponse;
  deleteContelloRoute: Scalars['String']['output'];
  deleteStaticPage: ContelloEntityDeleteResponse;
  deleteStaticPages?: Maybe<Array<ContelloEntityDeleteResponse>>;
  /** Register messages in an i18n message collection by reference name. */
  registerContelloI18nMessages?: Maybe<ContelloI18nMessageRegisterResponse>;
  truncateContelloRoutes?: Maybe<ContelloBatchOperationResponse>;
  truncateStaticPages?: Maybe<ContelloBatchOperationResponse>;
  updateContelloRoute?: Maybe<ContelloRoute>;
  updateStaticPage?: Maybe<StaticPageEntity>;
  updateStaticPages?: Maybe<Array<StaticPageEntity>>;
};


export type RootMutationCreateContelloRouteArgs = {
  route: ContelloRouteInput;
};


export type RootMutationCreateContelloRoutesArgs = {
  requests?: InputMaybe<Array<ContelloRouteInput>>;
};


export type RootMutationCreateStaticPageArgs = {
  request: CreateStaticPageRequestInput;
};


export type RootMutationCreateStaticPagesArgs = {
  requests?: InputMaybe<Array<CreateStaticPageRequestInput>>;
};


export type RootMutationDeleteContelloAssetArgs = {
  id: Scalars['String']['input'];
};


export type RootMutationDeleteContelloRouteArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
};


export type RootMutationDeleteStaticPageArgs = {
  request: DeleteEntityByIdInput;
};


export type RootMutationDeleteStaticPagesArgs = {
  request: DeleteEntityByIdsInput;
};


export type RootMutationRegisterContelloI18nMessagesArgs = {
  collectionReferenceName: Scalars['String']['input'];
  deprecateUnmentioned?: InputMaybe<Scalars['Boolean']['input']>;
  messages: Array<ContelloI18nMessageInput>;
};


export type RootMutationUpdateContelloRouteArgs = {
  route: ContelloRouteInput;
};


export type RootMutationUpdateStaticPageArgs = {
  request: UpdateStaticPageRequestInput;
};


export type RootMutationUpdateStaticPagesArgs = {
  requests?: InputMaybe<Array<UpdateStaticPageRequestInput>>;
};

export type RootQuery = {
  __typename?: 'RootQuery';
  contelloAsset?: Maybe<ContelloAsset>;
  contelloAssets?: Maybe<Array<Maybe<ContelloAsset>>>;
  contelloDictionaries?: Maybe<Array<Maybe<ContelloDictionary>>>;
  contelloEntityModels?: Maybe<Array<Maybe<ContelloEntityModel>>>;
  /** Get i18n messages from a collection by reference name. */
  contelloI18nMessages?: Maybe<ContelloI18nMessagesResponse>;
  /** Health check query. Returns 'pong'. */
  contelloPing: PingResult;
  contelloProject?: Maybe<ContelloProject>;
  contelloRoute?: Maybe<ContelloRoute>;
  contelloRoutes?: Maybe<Array<Maybe<ContelloRoute>>>;
  staticPage?: Maybe<StaticPageEntity>;
  staticPages: StaticPagesResponseCollection;
};


export type RootQueryContelloAssetArgs = {
  request: ContelloAssetRequestInput;
};


export type RootQueryContelloAssetsArgs = {
  filter?: InputMaybe<ContelloAssetsFilterInput>;
  pagination?: InputMaybe<ContelloAssetsPaginationInput>;
};


export type RootQueryContelloDictionariesArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
  referenceName?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<ContelloDictionaryType>;
};


export type RootQueryContelloEntityModelsArgs = {
  id?: InputMaybe<Scalars['ID']['input']>;
  referenceName?: InputMaybe<Scalars['String']['input']>;
};


export type RootQueryContelloI18nMessagesArgs = {
  collectionReferenceName: Scalars['String']['input'];
  pagination?: InputMaybe<ContelloI18nMessagePaginationInput>;
};


export type RootQueryContelloRouteArgs = {
  request: ContelloRouteRequestInput;
};


export type RootQueryContelloRoutesArgs = {
  request?: InputMaybe<ContelloRoutesRequestInput>;
};


export type RootQueryStaticPageArgs = {
  request: GetEntityByIdInput;
};


export type RootQueryStaticPagesArgs = {
  request?: InputMaybe<StaticPagesRequestInput>;
};

export type RootSubscription = {
  __typename?: 'RootSubscription';
  contelloAssets?: Maybe<ContelloAsset>;
  /** Subscribe to all assets for the project in batches. */
  contelloAssetsBatch: Array<ContelloAsset>;
  /** Subscribe to real-time updates for i18n messages in a collection by reference name. */
  contelloI18nMessageUpdates?: Maybe<ContelloI18nMessageUpdate>;
  /** Subscribe to all i18n messages from a collection by reference name. */
  contelloI18nMessages?: Maybe<ContelloI18nMessage>;
  /** Subscribe to all i18n messages from a collection in batches. */
  contelloI18nMessagesBatch: Array<ContelloI18nMessage>;
  contelloRouteUpdates?: Maybe<ContelloRouteUpdate>;
  contelloRoutes?: Maybe<ContelloRoute>;
  /** Subscribe to all routes for the project in batches. */
  contelloRoutesBatch: Array<ContelloRoute>;
  /** Subscribe to real-time updates for all resource types. */
  contelloUpdates?: Maybe<ContelloUpdateEvent>;
  /** Subscribe to batched real-time updates for all resource types. */
  contelloUpdatesBatch?: Maybe<ContelloUpdateBatch>;
  staticPageUpdates?: Maybe<StaticPageEntityUpdate>;
  staticPages?: Maybe<StaticPageEntity>;
  staticPagesBatch: Array<StaticPageEntity>;
};


export type RootSubscriptionContelloAssetsBatchArgs = {
  chunkSize?: InputMaybe<Scalars['Int']['input']>;
};


export type RootSubscriptionContelloI18nMessageUpdatesArgs = {
  collectionReferenceName: Scalars['String']['input'];
};


export type RootSubscriptionContelloI18nMessagesArgs = {
  collectionReferenceName: Scalars['String']['input'];
};


export type RootSubscriptionContelloI18nMessagesBatchArgs = {
  chunkSize?: InputMaybe<Scalars['Int']['input']>;
  collectionReferenceName: Scalars['String']['input'];
};


export type RootSubscriptionContelloRoutesBatchArgs = {
  chunkSize?: InputMaybe<Scalars['Int']['input']>;
};


export type RootSubscriptionContelloUpdatesBatchArgs = {
  maxSize?: InputMaybe<Scalars['Int']['input']>;
  windowMs?: InputMaybe<Scalars['Int']['input']>;
};


export type RootSubscriptionStaticPagesArgs = {
  request?: InputMaybe<StaticPagesRequestInput>;
};


export type RootSubscriptionStaticPagesBatchArgs = {
  chunkSize?: InputMaybe<Scalars['Int']['input']>;
  request?: InputMaybe<StaticPagesRequestInput>;
};

export type SectionComponent = ContelloFlatComponent & {
  __typename?: 'SectionComponent';
  /** Used together with the `flat` directive to solve problem with recursion */
  _flatId?: Maybe<Scalars['String']['output']>;
  _flat_content?: Maybe<Array<ContelloComponent>>;
  content?: Maybe<Array<ContelloComponent>>;
  headline?: Maybe<Scalars['String']['output']>;
};

export type SectionComponentInput = {
  content?: InputMaybe<Array<InputMaybe<SectionContentMixedComponentArrayItemInput>>>;
  headline?: InputMaybe<Scalars['String']['input']>;
};

export type SectionContentMixedComponentArrayItemInput = {
  textComponent?: InputMaybe<TextComponentInput>;
};

export type StaticPageAttributes = {
  __typename?: 'StaticPageAttributes';
  _flat_content?: Maybe<Array<ContelloComponent>>;
  content?: Maybe<Array<ContelloComponent>>;
  /** Internal name */
  name?: Maybe<Scalars['String']['output']>;
};

export type StaticPageAttributesInput = {
  content?: InputMaybe<Array<InputMaybe<StaticPageContentMixedComponentArrayItemInput>>>;
  /** Internal name */
  name?: InputMaybe<Scalars['String']['input']>;
};

export type StaticPageContentMixedComponentArrayItemInput = {
  sectionComponent?: InputMaybe<SectionComponentInput>;
  textComponent?: InputMaybe<TextComponentInput>;
};

export type StaticPageEntity = ContelloEntityBase & {
  __typename?: 'StaticPageEntity';
  /** Entity data attributes */
  attributes: StaticPageAttributes;
  /** The date and time when the entity was created */
  createdAt: Scalars['DateTime']['output'];
  /** The ID of the entity */
  id: Scalars['ID']['output'];
  /** The internal name of the entity */
  internalName: Scalars['String']['output'];
  /** The ID of the entity model */
  modelId: Scalars['ID']['output'];
  /** Entity routes */
  routes: Array<ContelloRoute>;
  /** The date and time when the entity was last updated */
  updatedAt: Scalars['DateTime']['output'];
};

export type StaticPageEntityUpdate = {
  __typename?: 'StaticPageEntityUpdate';
  /** The updated entity */
  entity: StaticPageEntity;
  /** Entity mutation */
  mutation: ContelloMutation;
};

/** Collection filter input for Static page entities. */
export type StaticPagesFilterInput = {
  /** Filter by Created column. */
  created?: InputMaybe<DateTimeFilterInput>;
  /** Entity IDs to filter by. */
  ids?: InputMaybe<Array<InputMaybe<Scalars['ID']['input']>>>;
  /** Filter by Name column. */
  name?: InputMaybe<StringFilterInput>;
  /** Filter by Route column. */
  route?: InputMaybe<StringFilterInput>;
  /** Filter by Last update column. */
  updated?: InputMaybe<DateTimeFilterInput>;
};

export type StaticPagesRequestInput = {
  filter?: InputMaybe<StaticPagesFilterInput>;
  pagination?: InputMaybe<PaginationInput>;
};

export type StaticPagesResponseCollection = {
  __typename?: 'StaticPagesResponseCollection';
  entities: Array<StaticPageEntity>;
  pagination: Pagination;
};

/** Filter input for string columns. */
export type StringFilterInput = {
  contains?: InputMaybe<Scalars['String']['input']>;
  endsWith?: InputMaybe<Scalars['String']['input']>;
  equal?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<Scalars['String']['input']>>;
  notEqual?: InputMaybe<Scalars['String']['input']>;
  notIn?: InputMaybe<Array<Scalars['String']['input']>>;
  startsWith?: InputMaybe<Scalars['String']['input']>;
};

export type TargetEntityConfigInput = {
  /** The id of the target entity. */
  entityId: Scalars['String']['input'];
  /** The id of the target entity model. */
  entityModelId: Scalars['String']['input'];
};

export type TargetFileConfig = {
  /** File asset id. */
  assetId: Scalars['String']['input'];
  /** File content disposition. */
  contentDisposition: ContelloContentDispositionEnum;
};

export type TargetRedirectConfig = {
  /** Redirect location. */
  location: Scalars['String']['input'];
  /** Redirect response code. */
  responseCode: Scalars['Int']['input'];
};

export type TargetTextResponseConfig = {
  /** Text response content. */
  content: Scalars['String']['input'];
  /** Text response mime type. */
  mimeType: Scalars['String']['input'];
};

export type TextComponent = ContelloFlatComponent & {
  __typename?: 'TextComponent';
  /** Used together with the `flat` directive to solve problem with recursion */
  _flatId?: Maybe<Scalars['String']['output']>;
  text?: Maybe<ContelloRichText>;
};

export type TextComponentInput = {
  text?: InputMaybe<ContelloRichTextInput>;
};

export type UpdateStaticPageEntityInput = {
  /** Entity attributes. */
  attributes: StaticPageAttributesInput;
  createdAt?: InputMaybe<Scalars['DateTime']['input']>;
  id: Scalars['ID']['input'];
  /** Entity route. */
  route?: InputMaybe<ContelloEntityRouteInput>;
  updatedAt?: InputMaybe<Scalars['DateTime']['input']>;
};

/** Entity update request. */
export type UpdateStaticPageRequestInput = {
  /** Entity data input. */
  entity: UpdateStaticPageEntityInput;
};

type Component_SectionComponent_Fragment = { __typename: 'SectionComponent', headline?: string | null, _flatId?: string | null, content?: Array<
    | { __typename: 'SectionComponent', _flatId?: string | null }
    | { __typename: 'TextComponent', _flatId?: string | null }
  > | null };

type Component_TextComponent_Fragment = { __typename: 'TextComponent', _flatId?: string | null, text?: { __typename?: 'ContelloRichText', markdownData?: string | null } | null };

export type ComponentFragment =
  | Component_SectionComponent_Fragment
  | Component_TextComponent_Fragment
;

type FlatComponent_SectionComponent_Fragment = { __typename: 'SectionComponent', _flatId?: string | null };

type FlatComponent_TextComponent_Fragment = { __typename: 'TextComponent', _flatId?: string | null };

export type FlatComponentFragment =
  | FlatComponent_SectionComponent_Fragment
  | FlatComponent_TextComponent_Fragment
;

export type GetStaticPagesQueryVariables = Exact<{
  request?: InputMaybe<StaticPagesRequestInput>;
}>;


export type GetStaticPagesQuery = { __typename?: 'RootQuery', staticPages: { __typename?: 'StaticPagesResponseCollection', entities: Array<{ __typename?: 'StaticPageEntity', id: string, internalName: string, routes: Array<{ __typename?: 'ContelloRoute', path: string }>, attributes: { __typename?: 'StaticPageAttributes', name?: string | null, content?: Array<
          | { __typename: 'SectionComponent', _flatId?: string | null }
          | { __typename: 'TextComponent', _flatId?: string | null }
        > | null, _flat_content?: Array<
          | { __typename: 'SectionComponent', headline?: string | null, _flatId?: string | null, content?: Array<
              | { __typename: 'SectionComponent', _flatId?: string | null }
              | { __typename: 'TextComponent', _flatId?: string | null }
            > | null }
          | { __typename: 'TextComponent', _flatId?: string | null, text?: { __typename?: 'ContelloRichText', markdownData?: string | null } | null }
        > | null } }> } };

export const FlatComponentFragmentDoc = gql`
    fragment FlatComponent on ContelloComponent {
  __typename
  ... on ContelloFlatComponent {
    _flatId
  }
}
    `;
export const ComponentFragmentDoc = gql`
    fragment Component on ContelloComponent {
  ...FlatComponent
  ... on TextComponent {
    text {
      markdownData
    }
  }
  ... on SectionComponent {
    headline
    content {
      ...FlatComponent
    }
  }
}
    ${FlatComponentFragmentDoc}`;
export const GetStaticPagesDocument = gql`
    query GetStaticPages($request: StaticPagesRequestInput) {
  staticPages(request: $request) {
    entities {
      id
      internalName
      routes {
        path
      }
      attributes {
        name
        content {
          ...FlatComponent
        }
        _flat_content {
          ...Component
        }
      }
    }
  }
}
    ${FlatComponentFragmentDoc}
${ComponentFragmentDoc}`;
export type Requester<C = {}, E = unknown> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<ExecutionResult<R, E>> | Observable<ExecutionResult<R, E>>
export function getSdk<C, E>(requester: Requester<C, E>) {
  return {
    GetStaticPages(variables?: GetStaticPagesQueryVariables, options?: C): Promise<ExecutionResult<GetStaticPagesQuery, E>> {
      return requester<GetStaticPagesQuery, GetStaticPagesQueryVariables>(GetStaticPagesDocument, variables, options) as Promise<ExecutionResult<GetStaticPagesQuery, E>>;
    }
  };
}
export type Sdk = ReturnType<typeof getSdk>;