/* eslint-disable */
// @ts-nocheck
/* this file is generated by contello-client — do not edit */

export type ContelloAssetKind = 'AUDIO' | 'DOCUMENT' | 'IMAGE' | 'OTHER' | 'VIDEO';
export type ContelloBatchOperationStatus = 'error' | 'success';
export type ContelloContentDispositionEnum = 'ATTACHMENT' | 'AUTOMATIC' | 'INLINE';
export type ContelloDictionaryType = 'ENTITY' | 'STATIC';
export type ContelloMutationType = 'CREATE' | 'DELETE' | 'UPDATE';
export type ContelloRouteTargetTypeEnum = 'ENTITY' | 'FILE' | 'REDIRECT' | 'TEXT_RESPONSE';
export type SectionAppearanceStaticDictionary = 'dark' | 'light';
export type ShippingOptionsStaticDictionary = 'delivery' | 'selfPickup';

export type CategoriesFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type CategoriesRequestInput = {
  filter?: CategoriesFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type CategoryAttributesInput = {
  name?: string | undefined;
};

export type ContelloAnnotationFilterInput = {
  key?: string | undefined;
  value?: string | undefined;
};

export type ContelloAssetInput = {
  assetId: string;
};

export type ContelloAssetRequestInput = {
  id?: string | undefined;
};

export type ContelloAssetsFilterInput = {
  annotations?: (ContelloAnnotationFilterInput | undefined)[] | undefined;
  collectionReferences?: (string | undefined)[] | undefined;
  ids?: (string | undefined)[] | undefined;
  kinds?: (ContelloAssetKind | undefined)[] | undefined;
};

export type ContelloAssetsPaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ContelloEntityRouteInput = {
  path: string;
};

export type ContelloI18nMessageInput = {
  description?: string | undefined;
  example?: string | undefined;
  initialTranslations?: ContelloI18nMessageTranslationValueInput[] | undefined;
  token: string;
  translations?: ContelloI18nMessageTranslationValueInput[] | undefined;
  variables?: ContelloI18nMessageVariableInput[] | undefined;
};

export type ContelloI18nMessagePaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ContelloI18nMessageTranslationValueInput = {
  language: string;
  message: string;
};

export type ContelloI18nMessageVariableInput = {
  description?: string | undefined;
  example?: string | undefined;
  name: string;
};

export type ContelloRichTextInput = {
  _markdownData?: string | undefined;
  _serializedData?: string | undefined;
  serializedData?: string | undefined;
};

export type ContelloRouteHeaderInput = {
  name: string;
  value: string;
};

export type ContelloRouteInput = {
  customHeaders?: (ContelloRouteHeaderInput | undefined)[] | undefined;
  path: string;
  targetEntityConfig?: TargetEntityConfigInput | undefined;
  targetFileConfig?: TargetFileConfig | undefined;
  targetRedirectConfig?: TargetRedirectConfig | undefined;
  targetTextResponseConfig?: TargetTextResponseConfig | undefined;
  targetType: ContelloRouteTargetTypeEnum;
};

export type ContelloRouteRequestInput = {
  id?: string | undefined;
  path?: string | undefined;
};

export type ContelloRoutesRequestInput = {
  ids?: (string | undefined)[] | undefined;
  paths?: (string | undefined)[] | undefined;
  targetType?: ContelloRouteTargetTypeEnum | undefined;
};

export type CreateCategoryEntityInput = {
  attributes: CategoryAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateCategoryRequestInput = {
  entity: CreateCategoryEntityInput;
};

export type CreateProductEntityInput = {
  attributes: ProductAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateProductRequestInput = {
  entity: CreateProductEntityInput;
};

export type CreateStaticPageEntityInput = {
  attributes: StaticPageAttributesInput;
  createdAt?: string | undefined;
  id?: string | undefined;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type CreateStaticPageRequestInput = {
  entity: CreateStaticPageEntityInput;
};

export type DateTimeFilterInput = {
  between?: DateTimeRangeInput | undefined;
  equal?: string | undefined;
  exists?: boolean | undefined;
  greaterThan?: string | undefined;
  greaterThanEqual?: string | undefined;
  lessThan?: string | undefined;
  lessThanEqual?: string | undefined;
  notEqual?: string | undefined;
};

export type DateTimeRangeInput = {
  from: string;
  to: string;
};

export type DeleteEntityByIdInput = {
  force?: boolean | undefined;
  id: string;
};

export type DeleteEntityByIdsInput = {
  ids: string[];
};

export type GetEntityByIdInput = {
  id: string;
};

export type PaginationInput = {
  limit?: number | undefined;
  offset?: number | undefined;
};

export type ProductAttributesInput = {
  category?: string | undefined;
  description?: ContelloRichTextInput | undefined;
  image?: ContelloAssetInput | undefined;
  name?: string | undefined;
  shipping?: (ShippingOptionsStaticDictionary | undefined)[] | undefined;
};

export type ProductListComponentInput = {
  headline?: string | undefined;
  products?: (string | undefined)[] | undefined;
};

export type ProductsFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type ProductsRequestInput = {
  filter?: ProductsFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type SectionComponentInput = {
  appearance?: SectionAppearanceStaticDictionary | undefined;
  content?: (SectionContentMixedComponentArrayItemInput | undefined)[] | undefined;
  headline?: string | undefined;
};

export type SectionContentMixedComponentArrayItemInput = {
  textComponent?: TextComponentInput | undefined;
};

export type StaticPageAttributesInput = {
  content?: (StaticPageContentMixedComponentArrayItemInput | undefined)[] | undefined;
  name?: string | undefined;
};

export type StaticPageContentMixedComponentArrayItemInput = {
  productListComponent?: ProductListComponentInput | undefined;
  sectionComponent?: SectionComponentInput | undefined;
  textComponent?: TextComponentInput | undefined;
};

export type StaticPagesFilterInput = {
  created?: DateTimeFilterInput | undefined;
  ids?: (string | undefined)[] | undefined;
  name?: StringFilterInput | undefined;
  route?: StringFilterInput | undefined;
  updated?: DateTimeFilterInput | undefined;
};

export type StaticPagesRequestInput = {
  filter?: StaticPagesFilterInput | undefined;
  pagination?: PaginationInput | undefined;
};

export type StringFilterInput = {
  contains?: string | undefined;
  endsWith?: string | undefined;
  equal?: string | undefined;
  exists?: boolean | undefined;
  in?: string[] | undefined;
  notEqual?: string | undefined;
  notIn?: string[] | undefined;
  startsWith?: string | undefined;
};

export type TargetEntityConfigInput = {
  entityId: string;
  entityModelId: string;
};

export type TargetFileConfig = {
  assetId: string;
  contentDisposition: ContelloContentDispositionEnum;
};

export type TargetRedirectConfig = {
  location: string;
  responseCode: number;
};

export type TargetTextResponseConfig = {
  content: string;
  mimeType: string;
};

export type TextComponentInput = {
  text?: ContelloRichTextInput | undefined;
};

export type UpdateCategoryEntityInput = {
  attributes: CategoryAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateCategoryRequestInput = {
  entity: UpdateCategoryEntityInput;
};

export type UpdateProductEntityInput = {
  attributes: ProductAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateProductRequestInput = {
  entity: UpdateProductEntityInput;
};

export type UpdateStaticPageEntityInput = {
  attributes: StaticPageAttributesInput;
  createdAt?: string | undefined;
  id: string;
  route?: ContelloEntityRouteInput | undefined;
  updatedAt?: string | undefined;
};

export type UpdateStaticPageRequestInput = {
  entity: UpdateStaticPageEntityInput;
};

export type CategoriesResponseCollection = {
  __typename?: 'CategoriesResponseCollection' | undefined;
  entities: CategoryEntity[];
  pagination: Pagination;
};

export type CategoryAttributes = {
  __typename?: 'CategoryAttributes' | undefined;
  name?: string | undefined;
};

export type CategoryEntity = {
  __typename?: 'CategoryEntity' | undefined;
  __model?: 'category' | undefined;
  attributes: CategoryAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type CategoryEntityUpdate = {
  __typename?: 'CategoryEntityUpdate' | undefined;
  entity: CategoryEntity;
  mutation: ContelloMutation;
};

export type ContelloAsset = {
  __typename?: 'ContelloAsset' | undefined;
  annotations: ContelloAssetAnnotation[];
  createdAt: string;
  id: string;
  optimized: ContelloOptimizedFile[];
  original: ContelloFile;
  preview?: ContelloFile | undefined;
  updatedAt: string;
};

export type ContelloAssetAnnotation = {
  __typename?: 'ContelloAssetAnnotation' | undefined;
  key: string;
  value: string;
};

export type ContelloAssetDeleteResponse = {
  __typename?: 'ContelloAssetDeleteResponse' | undefined;
  id: string;
  status: ContelloBatchOperationStatus;
};

export type ContelloBatchOperationResponse = {
  __typename?: 'ContelloBatchOperationResponse' | undefined;
  status: ContelloBatchOperationStatus;
};

export type ContelloDictionary = {
  __typename?: 'ContelloDictionary' | undefined;
  createdAt: string;
  description?: string | undefined;
  id: string;
  items?: (string | undefined)[] | undefined;
  name: string;
  referenceName: string;
  type: ContelloDictionaryType;
  updatedAt: string;
};

export type ContelloEntityDeleteResponse = {
  __typename?: 'ContelloEntityDeleteResponse' | undefined;
  id: string;
  status: ContelloBatchOperationStatus;
};

export type ContelloEntityModel = {
  __typename?: 'ContelloEntityModel' | undefined;
  description: string;
  id: string;
  isRoutable: boolean;
  name: string;
  referenceName: string;
};

export type ContelloI18nMessage = {
  __typename?: 'ContelloI18nMessage' | undefined;
  collectionId: string;
  createdAt: string;
  deprecated: boolean;
  description?: string | undefined;
  example?: string | undefined;
  id: string;
  token: string;
  translations: ContelloI18nMessageTranslation[];
  updatedAt: string;
  variables?: ContelloI18nMessageVariable[] | undefined;
};

export type ContelloI18nMessagePagination = {
  __typename?: 'ContelloI18nMessagePagination' | undefined;
  limit: number;
  offset: number;
  total: number;
};

export type ContelloI18nMessageRegisterResponse = {
  __typename?: 'ContelloI18nMessageRegisterResponse' | undefined;
  ids: string[];
};

export type ContelloI18nMessagesResponse = {
  __typename?: 'ContelloI18nMessagesResponse' | undefined;
  items: ContelloI18nMessage[];
  pagination: ContelloI18nMessagePagination;
};

export type ContelloI18nMessageTranslation = {
  __typename?: 'ContelloI18nMessageTranslation' | undefined;
  language: string;
  value: string;
};

export type ContelloI18nMessageUpdate = {
  __typename?: 'ContelloI18nMessageUpdate' | undefined;
  message: ContelloI18nMessage;
  mutation: ContelloMutation;
};

export type ContelloI18nMessageVariable = {
  __typename?: 'ContelloI18nMessageVariable' | undefined;
  description?: string | undefined;
  example?: string | undefined;
  name: string;
};

export type ContelloImageMetadata = {
  __typename?: 'ContelloImageMetadata' | undefined;
  height: number;
  width: number;
};

export type ContelloImageOptimizationConfig = {
  __typename?: 'ContelloImageOptimizationConfig' | undefined;
  name: string;
};

export type ContelloMutation = {
  __typename?: 'ContelloMutation' | undefined;
  type: ContelloMutationType;
};

export type ContelloOptimizedFile = {
  __typename?: 'ContelloOptimizedFile' | undefined;
  fileName: string;
  metadata?: ContelloFileMetadata | undefined;
  mimeType: string;
  optimizationConfig?: ContelloOptimizationConfig | undefined;
  uid: string;
};

export type ContelloProject = {
  __typename?: 'ContelloProject' | undefined;
  description: string;
  id: string;
  name: string;
  referenceName: string;
};

export type ContelloRichText = {
  __typename?: 'ContelloRichText' | undefined;
  markdownData?: string | undefined;
  serializedData?: string | undefined;
};

export type ContelloRoute = {
  __typename?: 'ContelloRoute' | undefined;
  createdAt: string;
  customHeaders: ContelloRouteHeader[];
  id: string;
  path: string;
  target: ContelloRouteTarget;
  updatedAt: string;
};

export type ContelloRouteHeader = {
  __typename?: 'ContelloRouteHeader' | undefined;
  name: string;
  value: string;
};

export type ContelloRouteTargetAsset = {
  __typename?: 'ContelloRouteTargetAsset' | undefined;
  asset: ContelloAsset;
  contentDisposition: ContelloContentDispositionEnum;
};

export type ContelloRouteTargetEntity = {
  __typename?: 'ContelloRouteTargetEntity' | undefined;
  entity?: ContelloEntityBase | undefined;
};

export type ContelloRouteTargetRedirect = {
  __typename?: 'ContelloRouteTargetRedirect' | undefined;
  location: string;
  responseCode: number;
};

export type ContelloRouteTargetText = {
  __typename?: 'ContelloRouteTargetText' | undefined;
  content: string;
  mimeType: string;
};

export type ContelloRouteUpdate = {
  __typename?: 'ContelloRouteUpdate' | undefined;
  mutation: ContelloMutation;
  route: ContelloRoute;
};

export type ContelloUpdateBatch = {
  __typename?: 'ContelloUpdateBatch' | undefined;
  events: ContelloUpdateEvent[];
};

export type ContelloUpdateEvent = {
  __typename?: 'ContelloUpdateEvent' | undefined;
  mutation: ContelloMutation;
  prev?: ContelloUpdatePrev | undefined;
  target: ContelloUpdateTarget;
};

export type ContelloVideoMetadata = {
  __typename?: 'ContelloVideoMetadata' | undefined;
  height: number;
  width: number;
};

export type ContelloVideoOptimizationConfig = {
  __typename?: 'ContelloVideoOptimizationConfig' | undefined;
  name: string;
};

export type Pagination = {
  __typename?: 'Pagination' | undefined;
  limit: number;
  offset: number;
  total: number;
};

export type PingResult = {
  __typename?: 'PingResult' | undefined;
  response: string;
};

export type ProductAttributes = {
  __typename?: 'ProductAttributes' | undefined;
  category?: CategoryEntity | undefined;
  description?: ContelloRichText | undefined;
  image?: ContelloAsset | undefined;
  name?: string | undefined;
  shipping?: ShippingOptionsStaticDictionary[] | undefined;
};

export type ProductEntity = {
  __typename?: 'ProductEntity' | undefined;
  __model?: 'product' | undefined;
  attributes: ProductAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type ProductEntityUpdate = {
  __typename?: 'ProductEntityUpdate' | undefined;
  entity: ProductEntity;
  mutation: ContelloMutation;
};

export type ProductListComponent = {
  __typename?: 'ProductListComponent' | undefined;
  __model?: 'productList' | undefined;
  _flatId?: string | undefined;
  headline?: string | undefined;
  products?: ProductEntity[] | undefined;
};

export type ProductsResponseCollection = {
  __typename?: 'ProductsResponseCollection' | undefined;
  entities: ProductEntity[];
  pagination: Pagination;
};

export type RootMutation = {
  __typename?: 'RootMutation' | undefined;
  createCategories?: CategoryEntity[] | undefined;
  createCategory?: CategoryEntity | undefined;
  createContelloRoute?: ContelloRoute | undefined;
  createContelloRoutes?: ContelloRoute[] | undefined;
  createProduct?: ProductEntity | undefined;
  createProducts?: ProductEntity[] | undefined;
  createStaticPage?: StaticPageEntity | undefined;
  createStaticPages?: StaticPageEntity[] | undefined;
  deleteCategories?: ContelloEntityDeleteResponse[] | undefined;
  deleteCategory: ContelloEntityDeleteResponse;
  deleteContelloAsset: ContelloAssetDeleteResponse;
  deleteContelloRoute: string;
  deleteProduct: ContelloEntityDeleteResponse;
  deleteProducts?: ContelloEntityDeleteResponse[] | undefined;
  deleteStaticPage: ContelloEntityDeleteResponse;
  deleteStaticPages?: ContelloEntityDeleteResponse[] | undefined;
  registerContelloI18nMessages?: ContelloI18nMessageRegisterResponse | undefined;
  truncateCategories?: ContelloBatchOperationResponse | undefined;
  truncateContelloRoutes?: ContelloBatchOperationResponse | undefined;
  truncateProducts?: ContelloBatchOperationResponse | undefined;
  truncateStaticPages?: ContelloBatchOperationResponse | undefined;
  updateCategories?: CategoryEntity[] | undefined;
  updateCategory?: CategoryEntity | undefined;
  updateContelloRoute?: ContelloRoute | undefined;
  updateProduct?: ProductEntity | undefined;
  updateProducts?: ProductEntity[] | undefined;
  updateStaticPage?: StaticPageEntity | undefined;
  updateStaticPages?: StaticPageEntity[] | undefined;
};

export type RootQuery = {
  __typename?: 'RootQuery' | undefined;
  categories: CategoriesResponseCollection;
  category?: CategoryEntity | undefined;
  contelloAsset?: ContelloAsset | undefined;
  contelloAssets?: (ContelloAsset | undefined)[] | undefined;
  contelloDictionaries?: (ContelloDictionary | undefined)[] | undefined;
  contelloEntityModels?: (ContelloEntityModel | undefined)[] | undefined;
  contelloI18nMessages?: ContelloI18nMessagesResponse | undefined;
  contelloPing: PingResult;
  contelloProject?: ContelloProject | undefined;
  contelloRoute?: ContelloRoute | undefined;
  contelloRoutes?: (ContelloRoute | undefined)[] | undefined;
  product?: ProductEntity | undefined;
  products: ProductsResponseCollection;
  staticPage?: StaticPageEntity | undefined;
  staticPages: StaticPagesResponseCollection;
};

export type RootSubscription = {
  __typename?: 'RootSubscription' | undefined;
  categories?: CategoryEntity | undefined;
  categoriesBatch: CategoryEntity[];
  categoryUpdates?: CategoryEntityUpdate | undefined;
  contelloAssets?: ContelloAsset | undefined;
  contelloAssetsBatch: ContelloAsset[];
  contelloI18nMessages?: ContelloI18nMessage | undefined;
  contelloI18nMessagesBatch: ContelloI18nMessage[];
  contelloI18nMessageUpdates?: ContelloI18nMessageUpdate | undefined;
  contelloRoutes?: ContelloRoute | undefined;
  contelloRoutesBatch: ContelloRoute[];
  contelloRouteUpdates?: ContelloRouteUpdate | undefined;
  contelloUpdates?: ContelloUpdateEvent | undefined;
  contelloUpdatesBatch?: ContelloUpdateBatch | undefined;
  products?: ProductEntity | undefined;
  productsBatch: ProductEntity[];
  productUpdates?: ProductEntityUpdate | undefined;
  staticPages?: StaticPageEntity | undefined;
  staticPagesBatch: StaticPageEntity[];
  staticPageUpdates?: StaticPageEntityUpdate | undefined;
};

export type SectionComponent = {
  __typename?: 'SectionComponent' | undefined;
  __model?: 'section' | undefined;
  _flat_content?: ContelloComponent[] | undefined;
  _flatId?: string | undefined;
  appearance?: SectionAppearanceStaticDictionary | undefined;
  content?: ContelloComponent[] | undefined;
  headline?: string | undefined;
};

export type StaticPageAttributes = {
  __typename?: 'StaticPageAttributes' | undefined;
  _flat_content?: ContelloComponent[] | undefined;
  content?: ContelloComponent[] | undefined;
  name?: string | undefined;
};

export type StaticPageEntity = {
  __typename?: 'StaticPageEntity' | undefined;
  __model?: 'staticPage' | undefined;
  attributes: StaticPageAttributes;
  createdAt: string;
  id: string;
  internalName: string;
  modelId: string;
  routes: ContelloRoute[];
  updatedAt: string;
};

export type StaticPageEntityUpdate = {
  __typename?: 'StaticPageEntityUpdate' | undefined;
  entity: StaticPageEntity;
  mutation: ContelloMutation;
};

export type StaticPagesResponseCollection = {
  __typename?: 'StaticPagesResponseCollection' | undefined;
  entities: StaticPageEntity[];
  pagination: Pagination;
};

export type TextComponent = {
  __typename?: 'TextComponent' | undefined;
  __model?: 'text' | undefined;
  _flatId?: string | undefined;
  text?: ContelloRichText | undefined;
};

export type ContelloEntityBase = {
  __typename?: string | undefined;
  createdAt: string;
  id: string;
  updatedAt: string;
};

export type ContelloFile = {
  __typename?: string | undefined;
  fileName: string;
  metadata?: ContelloFileMetadata | undefined;
  mimeType: string;
  uid: string;
};

export type ContelloFlatComponent = {
  __typename?: string | undefined;
  _flatId?: string | undefined;
};

export type ContelloComponent = ProductListComponent | SectionComponent | TextComponent;
export type ContelloEntity = CategoryEntity | ProductEntity | StaticPageEntity;
export type ContelloFileMetadata = ContelloImageMetadata | ContelloVideoMetadata;
export type ContelloOptimizationConfig = ContelloImageOptimizationConfig | ContelloVideoOptimizationConfig;
export type ContelloRouteTarget = ContelloRouteTargetAsset | ContelloRouteTargetEntity | ContelloRouteTargetRedirect | ContelloRouteTargetText;
export type ContelloUpdatePrev = ContelloRoute;
export type ContelloUpdateTarget = CategoryEntity | ContelloAsset | ContelloI18nMessage | ContelloRoute | ProductEntity | StaticPageEntity;

export const models = {
  category: 'CategoryEntity',
  product: 'ProductEntity',
  staticPage: 'StaticPageEntity',
} as const;

export type ModelType = keyof typeof models;

export type StoreFileFragment = {
  uid: string;
  mimeType: string;
  metadata?: {
    __typename: 'ContelloImageMetadata';
    width: number;
    height: number;
  } | {
    __typename: 'ContelloVideoMetadata';
    width: number;
    height: number;
  } | undefined;
};

export type StoreAssetFragment = {
  id: string;
  original: {
    uid: string;
    mimeType: string;
    metadata?: {
      __typename: 'ContelloImageMetadata';
      width: number;
      height: number;
    } | {
      __typename: 'ContelloVideoMetadata';
      width: number;
      height: number;
    } | undefined;
  };
  preview?: {
    uid: string;
    mimeType: string;
    metadata?: {
      __typename: 'ContelloImageMetadata';
      width: number;
      height: number;
    } | {
      __typename: 'ContelloVideoMetadata';
      width: number;
      height: number;
    } | undefined;
  } | undefined;
  optimized: ({
    uid: string;
    mimeType: string;
    metadata?: {
      __typename: 'ContelloImageMetadata';
      width: number;
      height: number;
    } | {
      __typename: 'ContelloVideoMetadata';
      width: number;
      height: number;
    } | undefined;
  })[];
};

export type StoreRouteFragment = {
  id: string;
  path: string;
  target: {
    __typename: 'ContelloRouteTargetEntity';
    entity?: {
      __typename: string;
      id: string;
    } | undefined;
  } | {
    __typename: 'ContelloRouteTargetAsset';
    asset: {
      id: string;
      original: {
        uid: string;
        mimeType: string;
      };
    };
    contentDisposition: ContelloContentDispositionEnum;
  } | {
    __typename: 'ContelloRouteTargetRedirect';
    location: string;
    responseCode: number;
  } | {
    __typename: 'ContelloRouteTargetText';
    content: string;
    mimeType: string;
  };
  customHeaders: {
    name: string;
    value: string;
  }[];
};

export type ComponentFragment = {
  __typename: 'ProductListComponent';
  __model: 'productList';
  headline?: string | undefined;
  products?: {
    id: string;
  }[] | undefined;
} | {
  __typename: 'TextComponent';
  __model: 'text';
  text?: {
    markdownData?: string | undefined;
  } | undefined;
} | {
  __typename: 'SectionComponent';
  __model: 'section';
  headline?: string | undefined;
  content?: ({
    __typename: 'ProductListComponent';
    __model: 'productList';
    headline?: string | undefined;
    products?: {
      id: string;
    }[] | undefined;
  } | {
    __typename: 'TextComponent';
    __model: 'text';
    text?: {
      markdownData?: string | undefined;
    } | undefined;
  } | {
    __typename: 'SectionComponent';
    __model: 'section';
    headline?: string | undefined;
    content?: ComponentFragment[] | undefined;
  })[] | undefined;
};

export type GetAllCategoriesSubscription = {
  categoriesBatch: ({
    id: string;
    attributes: {
      name?: string | undefined;
    };
  })[];
};

export type GetAllCategoriesSubscriptionVariables = Record<string, never>;

export type GetProductsQuery = {
  products: {
    entities: ({
      id: string;
      internalName: string;
      routes: {
        path: string;
      }[];
      attributes: {
        name?: string | undefined;
        description?: {
          markdownData?: string | undefined;
        } | undefined;
        image?: {
          id: string;
          original: {
            uid: string;
            mimeType: string;
            metadata?: {
              __typename: 'ContelloImageMetadata';
              width: number;
              height: number;
            } | {
              __typename: 'ContelloVideoMetadata';
              width: number;
              height: number;
            } | undefined;
          };
          preview?: {
            uid: string;
            mimeType: string;
            metadata?: {
              __typename: 'ContelloImageMetadata';
              width: number;
              height: number;
            } | {
              __typename: 'ContelloVideoMetadata';
              width: number;
              height: number;
            } | undefined;
          } | undefined;
          optimized: ({
            uid: string;
            mimeType: string;
            metadata?: {
              __typename: 'ContelloImageMetadata';
              width: number;
              height: number;
            } | {
              __typename: 'ContelloVideoMetadata';
              width: number;
              height: number;
            } | undefined;
          })[];
        } | undefined;
        category?: {
          id: string;
        } | undefined;
      };
    })[];
  };
};

export type GetProductsQueryVariables = {
  request?: ProductsRequestInput | undefined;
};

export type GetStaticPagesQuery = {
  staticPages: {
    entities: ({
      id: string;
      internalName: string;
      routes: {
        path: string;
      }[];
      attributes: {
        name?: string | undefined;
        content?: ({
          __typename: 'ProductListComponent';
          __model: 'productList';
          headline?: string | undefined;
          products?: {
            id: string;
          }[] | undefined;
        } | {
          __typename: 'TextComponent';
          __model: 'text';
          text?: {
            markdownData?: string | undefined;
          } | undefined;
        } | {
          __typename: 'SectionComponent';
          __model: 'section';
          headline?: string | undefined;
          content?: ComponentFragment[] | undefined;
        })[] | undefined;
      };
    })[];
  };
};

export type GetStaticPagesQueryVariables = {
  request?: StaticPagesRequestInput | undefined;
};

export const getAllCategoriesDocument = `subscription GetAllCategories {
  categoriesBatch {
    id
    attributes {
      name
    }
  }
}`;

export const getProductsDocument = `fragment StoreFile on ContelloFile {
  uid
  mimeType
  metadata {
    ... on ContelloImageMetadata {
      width
      height
    }
    ... on ContelloVideoMetadata {
      width
      height
    }
  }
}
fragment StoreAsset on ContelloAsset {
  id
  original {
    ...StoreFile
  }
  preview {
    ...StoreFile
  }
  optimized {
    ...StoreFile
  }
}
query GetProducts($request: ProductsRequestInput) {
  products(request: $request) {
    entities {
      id
      internalName
      routes {
        path
      }
      attributes {
        name
        description {
          markdownData
        }
        image {
          ...StoreAsset
        }
        category {
          id
        }
      }
    }
  }
}`;

export const getStaticPagesDocument = `fragment Component on ContelloComponent {
  __typename
  ... on ContelloFlatComponent {
    _flatId
  }
  ... on ProductListComponent {
    headline
    products {
      id
    }
  }
  ... on TextComponent {
    text {
      markdownData
    }
  }
  ... on SectionComponent {
    headline
    content {
      __typename
      ... on ContelloFlatComponent {
        _flatId
      }
    }
  }
}
query GetStaticPages($request: StaticPagesRequestInput) {
  staticPages(request: $request) {
    entities {
      id
      internalName
      routes {
        path
      }
      attributes {
        name
        content {
          __typename
          ... on ContelloFlatComponent {
            _flatId
          }
        }
        _flat_content {
          __typename
          ... on ContelloFlatComponent {
            _flatId
          }
          ...Component
        }
      }
    }
  }
}`;

export type Operations = {
  getAllCategories: {
    document: string;
    kind: 'subscription';
    __result?: GetAllCategoriesSubscription | undefined;
    __variables?: GetAllCategoriesSubscriptionVariables | undefined;
  };
  getProducts: {
    document: string;
    kind: 'query';
    __result?: GetProductsQuery | undefined;
    __variables?: GetProductsQueryVariables | undefined;
  };
  getStaticPages: {
    document: string;
    kind: 'query';
    __result?: GetStaticPagesQuery | undefined;
    __variables?: GetStaticPagesQueryVariables | undefined;
  };
};

export const operations: Operations = {
  getAllCategories: { document: getAllCategoriesDocument, kind: 'subscription' },
  getProducts: { document: getProductsDocument, kind: 'query' },
  getStaticPages: { document: getStaticPagesDocument, kind: 'query' },
} as Operations;