fragment Component on ContelloComponent {
  ... on ProductListComponent {
    headline
    products {
      id
    }
  }

  ... on TextComponent {
    text {
      markdownData
    }
  }

  ... on SectionComponent {
    headline
    content {
      ...Component
    }
  }
}
