query GetProducts($request: ProductsRequestInput) {
  products(request: $request) {
    entities {
      id
      internalName
      routes {
        path
      }
      attributes {
        name
        description {
          markdownData
        }
        image {
          ...StoreAsset
        }
        category {
          id
        }
      }
    }
  }
}
