fragment Product on ProductEntity {
  id
  internalName
  routes {
    path
  }
  attributes {
    name
    activeSince
    bestBefore
    description {
      markdownData
    }
    image {
      ...StoreAsset
    }
    category {
      id
    }
  }
}
