import assert from 'assert';
import type { CodegenConfig } from '@graphql-codegen/cli';

const { CONTELLO_URL, CONTELLO_DEMO_ASTRO_PROJECT, CONTELLO_TOKEN } = process.env;

assert(CONTELLO_URL, 'CONTELLO_URL is required');
assert(CONTELLO_DEMO_ASTRO_PROJECT, 'CONTELLO_DEMO_ASTRO_PROJECT is required');
assert(CONTELLO_TOKEN, 'CONTELLO_TOKEN is required');

const generatedNote = `/* eslint-disable */
/* @ts-ignore */
/*

  This file is generated by graphql-codegen. Do not edit it manually.

*/`;

const config: CodegenConfig = {
  schema: {
    [`${CONTELLO_URL}/graphql/projects/${CONTELLO_DEMO_ASTRO_PROJECT}`]: {
      headers: {
        authorization: `Bearer ${CONTELLO_TOKEN}`,
      },
    },
  },
  generates: {
    'src/server/_/gql/graphql.ts': {
      documents: ['src/server/graphql/**/*.gql'],
      plugins: [{ add: { content: generatedNote } }, 'typescript', 'typescript-operations', 'typescript-generic-sdk'],
      config: {
        rawRequest: true,
        enumsAsTypes: true,
        usingObservableFrom: 'import { Observable } from "rxjs";',
        useTypeImports: true,
        dedupeFragments: true,
      },
    },
  },
};

export default config;
