import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { glob } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { parse } from 'graphql';

import { loadConfig } from './config';
import { collectFragments, collectOperations, generateDocumentString } from './documents';
import { introspectSchema } from './introspect';
import { generateFragmentTypes, generateOperationTypes } from './operation-types';
import { generateOperationsObject } from './operations';
import { generateSchemaTypes } from './schema-types';
import { transformFragment, transformOperation } from './transform-components';
import { uncapitalize } from './utils';

async function main(): Promise<void> {
  const cwd = process.cwd();
  const config = await loadConfig(cwd);

  for (const project of config.projects) {
    console.log(`generating types for project "${project.project}"...`);

    // remove stale output before generating
    rmSync(resolve(cwd, project.output), { force: true });

    // introspect schema
    const schema = await introspectSchema(project.url, project.project, project.token);

    // load .gql documents
    const patterns = Array.isArray(project.documents) ? project.documents : [project.documents];
    const documentPaths = (await Promise.all(patterns.map((p) => Array.fromAsync(glob(p, { cwd }))))).flat().sort();

    if (documentPaths.length === 0) {
      console.warn(`  no documents found matching "${project.documents}"`);

      continue;
    }

    const documents = documentPaths.map((p) => parse(readFileSync(resolve(cwd, p), 'utf-8')));
    const fragments = collectFragments(documents);
    const operations = collectOperations(documents);

    console.log(`  found ${operations.length} operations, ${fragments.size} fragments`);

    // transform component fields (auto-inject _flat_ pattern)
    const transformedFragments = new Map(
      [...fragments].map(([name, frag]) => [name, transformFragment(schema, frag, fragments)]),
    );

    const transformedOperations = operations.map((op) => transformOperation(schema, op, transformedFragments));

    // generate
    const parts: string[] = [];

    parts.push('/* eslint-disable */');
    parts.push('// @ts-nocheck');
    parts.push('/* this file is generated by contello-client — do not edit */');
    parts.push('');

    // schema types
    parts.push(generateSchemaTypes(schema));

    // fragment types (use original fragments for clean types)
    parts.push(generateFragmentTypes(schema, fragments));

    // operation result + variables types (use original operations for clean types)
    parts.push(generateOperationTypes(schema, operations, fragments));

    // document string constants (use TRANSFORMED for transport)
    for (let i = 0; i < operations.length; i++) {
      const camelName = uncapitalize(operations[i]!.name!.value);
      const docString = generateDocumentString(transformedOperations[i]!, transformedFragments);

      parts.push(`export const ${camelName}Document = \`${docString}\`;`);
      parts.push('');
    }

    // operations object with phantom types
    parts.push(generateOperationsObject(operations));

    let output = parts.join('\n');

    // optional namespace wrapping
    if (project.namespace) {
      const indented = output
        .split('\n')
        .map((line) => (line ? `  ${line}` : ''))
        .join('\n');

      output = `export namespace ${project.namespace} {\n${indented}\n}\n`;
    }

    // write output
    const outputPath = resolve(cwd, project.output);

    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, output, 'utf-8');

    console.log(`  wrote ${outputPath}`);
  }

  console.log('done');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
